name: Workflow1

on:
  push:
    branches:
      main

jobs:
  make_build_tag:
    runs-on: ubuntu-latest
    name: Creating build number tag based on version
    strategy:
      max-parallel: 1
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      # https://github.com/marohrdanz/extract-version-from-file
      # This action outputs the version number as 'version_number'.
      - name: Get version number
        id: get_version_number
        uses: marohrdanz/extract-version-from-file@v1.0.0
        with:
          file_path: 'CompatibilityManager.js'
          start_string: 'CM.version = '
      # https://github.com/marohrdanz/build-number-tag
      # This action outputs the tag name as 'build_number'.
      - name: Create Build Number Tag
        id: make_build_tag
        uses: marohrdanz/build-number-tag@v1.0.0
        with:
          token: ${{ secrets.TOKEN }}
          prefix: '-build-'
          version_prefix: ${{ steps.get_version_number.outputs.version_number }}
  build_artifacts:
    runs-on: ubuntu-latest
    name: Build Artifacts
    needs: make_build_tag
    strategy:
      max-parallel: 1
    env:
      Artifacts_REPOSITORY: 'marohrdanz/NG-CHM-Artifacts'
      Artifacts_BRANCH: 'main'
    steps:
      - name: latest commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Get Version Number
        uses: actions/github-script@v6
        with:
          script: |
            console.log("mary was here. build number is ", needs.make_build_tag.outputs.build_number);


            
