
name: Workflow2
on:
  workflow_run:
    workflows: [Workflow1]
    types: [completed]

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      max-parallel: 1
    env:
      Artifacts_REPOSITORY: 'marohrdanz/NG-CHM-Artifacts'
      Artifacts_BRANCH: 'main'
    steps:
      - name: latest commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client-payload.sha }}
      - name: Get Version Number
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            console.log("mary was here");
            console.log({allArtifacts});
            
