on:
  push:
    branches:
      main

jobs:
  make_build_tag:
    runs-on: ubuntu-latest
    name: Testing build number ideas
    steps:
      - name: Create Build Number Tag
        id: make_build_tag
        uses: marohrdanz/build-number-tag@main
        with:
          token: ${{ secrets.TOKEN }}
          prefix: 'a%22%3B%20ls%20%24GITHUB_WORKSPACE%22'
