on:
  push:
    branches:
      main

jobs:
  make_build_tag:
    runs-on: ubuntu-latest
    name: Testing build number ideas
    steps:
      - name: Hello world action step
        id: make_build_tag
        uses: marohrdanz/hello-world-javascript-action@main
        with:
          token: ${{ secrets.TOKEN }}
