on:
  push:
    branches:
      main

jobs:
  make_build_tag:
    runs-on: ubuntu-latest
    name: Testing build-number-tag action
    steps:
      - name: Create Build Number Tag
        id: make_build_tag
        uses: marohrdanz/build-number-tag@use-core
        with:
          token: ${{ secrets.TOKEN }}
          prefix: 'demo-tag'
      - name: Check output
        id: check_output
        run: |
           echo "Checking build output... ${{ steps.make_build_tag.outputs.build_number }}"
