on:
  push:
    branches:
      main

jobs:
  make_build_tag:
    runs-on: ubuntu-latest
    name: Testing build number ideas
    steps:
      - name: Create Build Number Tag
        id: make_build_tag
        uses: marohrdanz/build-number-tag@use-core
        with:
          token: ${{ secrets.TOKEN }}
