on:
  push:
    branches:
      main

jobs:
  make_build_tag:
    runs-on: ubuntu-latest
    name: Testing build-number-tag action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Get version number
        id: get_version_number
        uses: marohrdanz/extract-version-from-file@main
        with:
          file_path: 'CompatibilityManager.js'
          start_string: 'CM.version = '
      - name: Check output
        id: check_version_number
        run: |
           echo "Checking version number output... ${{ steps.get_version_number.outputs.version_number }}"
      - name: Create Build Number Tag
        id: make_build_tag
        uses: marohrdanz/build-number-tag@version-number
        with:
          token: ${{ secrets.TOKEN }}
          prefix: 'demo-tag-'
          version_prefix: '5.6.3'
      - name: Check output
        id: check_build_number
        run: |
           echo "Checking make tag output... ${{ steps.make_build_tag.outputs.build_number }}"
